version: '3.6'
services:
  postgres:
    image: postgres:9.6.9
    hostname: postgres
    container_name: tomotachi-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=adminadmin
      - POSTGRES_DB=tomotachi
    volumes:
      - ./data/db:/var/lib/postgresql/data

  tomatachi:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always

    ports:
      - 8080:8080
    links:
      - postgres
    depends_on:
      - postgres
    env_file:
      - .env.docker
